In [ ]:
import sys
import numpy as np
import requests 

# default varibales
nQueens = 8
STOP_CTR = 28
MUTATE = 0.000001
MUTATE_FLAG = True
MAX_ITER = 100000
POPULATION = None

In [ ]:
class BoardPosition:
	def __init__(self):
		self.sequence = None
		self.fitness = None
		self.survival = None
	def setSequence(self, val):
		self.sequence = val
	def setFitness(self, fitness):
		self.fitness = fitness
	def setSurvival(self, val):
		self.survival = val
	def getAttr(self):
		return {'sequence':sequence, 'fitness':fitness, 'survival':survival}

In [ ]:
def fitness(chromosome = None):
	clashes = 0;
	row_col_clashes = abs(len(chromosome) - len(np.unique(chromosome)))
	clashes += row_col_clashes

	# calculate diagonal clashes
	for i in range(len(chromosome)):
		for j in range(len(chromosome)):
			if ( i != j):
				dx = abs(i-j)
				dy = abs(chromosome[i] - chromosome[j])
				if(dx == dy):
					clashes += 1

	return 28 - clashes	

In [ ]:
def generateChromosome():
	global nQueens
	init_distribution = np.arange(nQueens)
	np.random.shuffle(init_distribution)
	return init_distribution

In [ ]:
def generatePopulation(population_size = 100):
	global POPULATION

	POPULATION = population_size

	population = [BoardPosition() for i in range(population_size)]
	for i in range(population_size):
		population[i].setSequence(generateChromosome())
		population[i].setFitness(fitness(population[i].sequence))

	return population

In [ ]:
def getParent():
	globals()	
	parent1, parent2 = None, None
	
	summation_fitness = np.sum([x.fitness for x in population])
	for each in population:
		each.survival = each.fitness/(summation_fitness*1.0)

	while True:
		parent1_random = np.random.rand()
		parent1_rn = [x for x in population if x.survival <= parent1_random]
		try:
			parent1 = parent1_rn[0]
			break
		except:
			pass

	while True:
		parent2_random = np.random.rand()
		parent2_rn = [x for x in population if x.survival <= parent2_random]
		try:
			t = np.random.randint(len(parent2_rn))
			parent2 = parent2_rn[t]
			if parent2 != parent1:
				break
			else:
				print("equal parents")
				continue
		except:
			print("exception")
			continue

	if parent1 is not None and parent2 is not None:
		return parent1, parent2
	else:
		sys.exit(-1)

In [ ]:
def reproduce_crossover(parent1, parent2):
	globals()
	n = len(parent1.sequence)
	c = np.random.randint(n, size=1)
	child = BoardPosition()
	child.sequence = []
	child.sequence.extend(parent1.sequence[0:c])
	child.sequence.extend(parent2.sequence[c:])
	child.setFitness(fitness(child.sequence))
	return child

In [ ]:
def mutate(child):
	if child.survival < MUTATE:
		c = np.random.randint(8)
		child.sequence[c] = np.random.randint(8)
	return child


In [ ]:
def GA(iteration):
	print(" #"*10 ,"Executing Genetic  generation : ", iteration , " #"*10)
	globals()
	newpopulation = []
	for i in range(len(population)):
		parent1, parent2 = getParent()
		print("Parents generated : ", parent1, parent2)

		child = reproduce_crossover(parent1, parent2)

		if(MUTATE_FLAG):
			child = mutate(child)

		newpopulation.append(child)
	return newpopulation

In [ ]:
def stop():
	globals()
	print(population[0], " printing population[0]")
	fitnessvals = [pos.fitness for pos in population]
	if STOP_CTR in fitnessvals:
		return True
	if MAX_ITER == iteration:
		return True
	return False
  

In [ ]:
population = generatePopulation(1000)

print("POPULATION size : ", population)

POPULATION size :  [<__main__.BoardPosition object at 0x7f7c48263c88>, <__main__.BoardPosition object at 0x7f7c48263cc0>, <__main__.BoardPosition object at 0x7f7c48263cf8>, <__main__.BoardPosition object at 0x7f7c48250da0>, <__main__.BoardPosition object at 0x7f7c48250470>, <__main__.BoardPosition object at 0x7f7c482507b8>, <__main__.BoardPosition object at 0x7f7c48250e48>, <__main__.BoardPosition object at 0x7f7c48250898>, <__main__.BoardPosition object at 0x7f7c482502b0>, <__main__.BoardPosition object at 0x7f7c48250be0>, <__main__.BoardPosition object at 0x7f7c48250160>, <__main__.BoardPosition object at 0x7f7c48250080>, <__main__.BoardPosition object at 0x7f7c482500f0>, <__main__.BoardPosition object at 0x7f7c48250048>, <__main__.BoardPosition object at 0x7f7c482500b8>, <__main__.BoardPosition object at 0x7f7c482505f8>, <__main__.BoardPosition object at 0x7f7c482504a8>, <__main__.BoardPosition object at 0x7f7c48250588>, <__main__.BoardPosition object at 0x7f7c482508d0>, <__main__.B

In [ ]:
iteration = 0;
while not stop():
	# keep iteratin till  you find the best position
	population = GA(iteration)
	iteration +=1 

print("Iteration number : ", iteration)
for each in population:
	if each.fitness == 28:
		print(each.sequence)

<__main__.BoardPosition object at 0x7f7c48263c88>  printing population[0]
Iteration number :  0
[4 6 0 2 7 5 3 1]
[4 6 1 5 2 0 7 3]
[5 0 4 1 7 2 6 3]


In [ ]:
import requests

url='https://lf8q0kx152.execute-api.us-east-2.amazonaws.com/default/computeFitnessScore'
x=requests.post(url,json={"qconfig":"4 6 0 2 7 5 3 1","userID":133731,"githubLink":"https://github.com/rahulrjk19/cts_ds_summit_2020/blob/master/8_queens_problem_ga.ipynb"})
print(x.text)

{"No Of Attempts lapsed out of 3": 1, "submittedConfiguration": [4, 6, 0, 2, 7, 5, 3, 1], "configurationStatus": "Valid", "configurationScore": 100.0}
